# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_3',
            field=models.CharField(blank=True, help_text='Street/Village', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Building/Flat/Plot No.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Area/Locality/Post', max_length=50, null=True),
        ),
    ]
