# Generated by Django 2.2 on 2020-04-18 10:51

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200410_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
    ]
