# Generated by Django 2.2 on 2020-04-26 16:21

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_allergy_disease_immunization_lifestyle_surgery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholAddiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
        migrations.CreateModel(
            name='HealthWorkerRegistrationAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
        migrations.CreateModel(
            name='PathlogyLabType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
    ]
