# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 07:55
from __future__ import unicode_literals

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20190420_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            bases=(common.models.ModelMixinForTextField, models.Model),
        ),
    ]
