# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('date_on', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('husband_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('-', ' -- '), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1)),
                ('registration_number', models.CharField(max_length=25)),
                ('years_of_experience', models.IntegerField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='documents/doctor/')),
                ('registration_certificate', models.FileField(upload_to='documents/doctor/')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='documents/doctor/')),
                ('Research', models.ManyToManyField(to='utility.Research')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Address')),
                ('associated_with', models.ManyToManyField(blank=True, null=True, to='organization.Organization')),
                ('languages_can_speak', models.ManyToManyField(to='utility.Language')),
                ('qualification', models.ManyToManyField(to='utility.Qualification')),
                ('specialization', models.ManyToManyField(to='utility.Specialization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthworkerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('husband_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('-', ' -- '), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1)),
                ('registration_number', models.CharField(max_length=25)),
                ('years_of_experience', models.IntegerField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='documents/healthworker/')),
                ('registration_certificate', models.FileField(upload_to='documents/healthworker/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='documents/healthworker/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Address')),
                ('associated_with', models.ManyToManyField(to='organization.Organization')),
                ('languages_can_speak', models.ManyToManyField(to='utility.Language')),
                ('qualification', models.ManyToManyField(to='utility.Qualification')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('husband_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('-', ' -- '), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1)),
                ('registration_certificate', models.FileField(upload_to='documents/medicalrepresentative/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='documents/medicalrepresentative/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Address')),
                ('associated_with', models.ManyToManyField(to='organization.Organization')),
                ('qualification', models.ManyToManyField(to='utility.Qualification')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('husband_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('-', ' -- '), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1)),
                ('case_summary', models.TextField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(help_text='in Kilogram')),
                ('height', models.PositiveIntegerField(help_text='in Centimeters')),
                ('aadhaar_no', models.PositiveIntegerField()),
                ('alternate_mobile_no', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_pic', models.FileField(upload_to='documents/patient/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Address')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.BloodGroup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.DoctorProfile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='healthworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.HealthworkerProfile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
