# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelBase64',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='documents/testing/')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        )
    ]
