# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helper.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_accreditation'),
        ('organization', '0003_auto_20190809_1847'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('appointment_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=10, validators=[helper.validators.mobile_validator])),
                ('consultation_fee', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offlineavailability_created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnlineAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('appointment_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=10, validators=[helper.validators.mobile_validator])),
                ('chat', models.BooleanField(default=False)),
                ('video_call', models.BooleanField(default=False)),
                ('voice_call', models.BooleanField(default=False)),
                ('chat_fee', models.PositiveIntegerField()),
                ('video_call_fee', models.PositiveIntegerField()),
                ('voice_call_fee', models.PositiveIntegerField()),
                ('chat_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('video_call_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('voice_call_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineavailability_created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutdoorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('appointment_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=10, validators=[helper.validators.mobile_validator])),
                ('outdoor_travel_upto', models.PositiveIntegerField(blank=True, null=True)),
                ('outdoor_travel_city', models.CharField(blank=True, max_length=50, null=True)),
                ('outdoor_travel_locality', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_0_to_5km', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_5_to_10km', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_10_to_15km', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_15_to_20km', models.PositiveIntegerField(blank=True, null=True)),
                ('fee_above_20km', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_0_to_5km', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_5_to_10km', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_10_to_15km', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_15_to_20km', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_above_20km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outdooravailability_created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='availability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='health_worker',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='outdoor_travel_state',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='venue',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthworkerprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healthworkerprofile_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthworkerprofile',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healthworkerprofile_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrepresentative',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalrepresentative_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrepresentative',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalrepresentative_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientprofile_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientprofile_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.AddField(
            model_name='outdooravailability',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outdooravailability', to='userprofile.DoctorProfile'),
        ),
        migrations.AddField(
            model_name='outdooravailability',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outdooravailability_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outdooravailability',
            name='outdoor_travel_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_availabilities', to='common.State'),
        ),
        migrations.AddField(
            model_name='onlineavailability',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onlineavailability', to='userprofile.DoctorProfile'),
        ),
        migrations.AddField(
            model_name='onlineavailability',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineavailability_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offlineavailability', to='userprofile.DoctorProfile'),
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offlineavailability_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offline_availabilities', to='organization.Organization'),
        ),
    ]
