# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190809_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineavailability',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='offlineavailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='offlineavailability',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='offlineavailability',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='onlineavailability',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='onlineavailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='onlineavailability',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='outdooravailability',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='outdooravailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='outdooravailability',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='outdooravailability',
            name='outdoor_travel_state',
        ),
        migrations.DeleteModel(
            name='OfflineAvailability',
        ),
        migrations.DeleteModel(
            name='OnlineAvailability',
        ),
        migrations.DeleteModel(
            name='OutdoorAvailability',
        ),
    ]
