# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20181208_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='languages_can_speak',
            field=models.ManyToManyField(blank=True, null=True, to='common.Language'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.ManyToManyField(blank=True, null=True, to='common.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='common.Specialization'),
        )
    ]
