# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20181208_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='registration_number',
            field=models.CharField(max_length=25, unique=True),
        )
    ]
