# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20181208_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='Research',
        )
    ]
