# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20190810_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineavailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offlineavailability', to='userprofile.DoctorProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineavailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onlineavailability', to='userprofile.DoctorProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outdooravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outdooravailability', to='userprofile.DoctorProfile'),
            preserve_default=False,
        )
    ]
