# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('userprofile', '0005_auto_20181208_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='research',
            field=models.ManyToManyField(blank=True, null=True, to='common.Research'),
        )
    ]
