# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190810_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='availabilityschedule',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='offlineavailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='offlineavailability',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='offlineavailability',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='onlineavailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='onlineavailability',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='outdooravailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='outdooravailability',
            name='outdoor_travel_state',
        ),
        migrations.RemoveField(
            model_name='outdooravailability',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='AvailabilitySchedule',
        ),
        migrations.DeleteModel(
            name='OfflineAvailability',
        ),
        migrations.DeleteModel(
            name='OnlineAvailability',
        ),
        migrations.DeleteModel(
            name='OutdoorAvailability',
        ),
    ]
