# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190126_1245'),
        ('userprofile', '0006_auto_20181208_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='documents/healthworker/'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.DoctorProfile'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='health_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.HealthworkerProfile'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Address'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Address'),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Address'),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Address'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.BloodGroup'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='in Centimeters', null=True),
        )
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='in Kilogram', null=True),
        ),
    ]
