# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('userprofile', '0006_auto_20181208_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrepresentative',
            name='languages_can_speak',
            field=models.ManyToManyField(to='common.Language'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='languages_can_speak',
            field=models.ManyToManyField(to='common.Language'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='documents/healthworker/'),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.BloodGroup'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='in Centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='in Kilogram', null=True),
        ),
    ]
