# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190126_1245'),
        ('userprofile', '0007_auto_20190126_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='authority_registered_with',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Address'),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Address'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Address'),
        )
    ]
