# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helper.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0007_auto_20190811_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='availabilityschedule',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='availabilityschedule',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='availabilityschedule',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='discount_0_to_5km',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='discount_10_to_15km',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='discount_15_to_20km',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='discount_5_to_10km',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='discount_above_20km',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='fee_0_to_5km',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='fee_10_to_15km',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='fee_15_to_20km',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='fee_5_to_10km',
        ),
        migrations.RemoveField(
            model_name='consultationdetails',
            name='fee_above_20km',
        ),
        migrations.AddField(
            model_name='consultationdetails',
            name='outdoor_additional_charges',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationdetails',
            name='outdoor_consultation_fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultationdetails',
            name='outdoor_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='contact_no_offline_consultation',
            field=models.CharField(default='', max_length=10, validators=[helper.validators.mobile_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offlineavailability_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offlineavailability_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='offline_consultation_fee',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offlineavailability',
            name='offline_discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineavailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineavailability_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineavailability',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineavailability',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineavailability_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineavailability',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outdooravailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outdooravailability_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outdooravailability',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outdooravailability',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outdooravailability_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outdooravailability',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        )
    ]
