# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import helper.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20190825_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineavailability',
            name='venue',
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='chat_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='contact_no_offline_consultation',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[helper.validators.mobile_validator]),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='contact_no_online_consultation',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[helper.validators.mobile_validator]),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='contact_no_outdoor_consultation',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[helper.validators.mobile_validator]),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='offline_consultation_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='outdoor_consultation_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='video_call_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='voice_call_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
