# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190126_1245'),
        ('userprofile', '0009_auto_20190210_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='outdoor_travel_city',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='outdoor_travel_locality',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='outdoor_travel_upto',
        )
    ]
