# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190809_1847'),
        ('userprofile', '0009_auto_20190825_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineavailability',
            name='venue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='offline_availabilities', to='organization.Organization'),
            preserve_default=False,
        )
    ]
