# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190126_1245'),
        ('userprofile', '0010_auto_20190210_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='outdoor_travel_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='outdoor_travel_locality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='outdoor_travel_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.State'),
        ),
        migrations.AddField(
            model_name='availability',
            name='outdoor_travel_upto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.Organization'),
        )
    ]
