# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-31 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import helper.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20190825_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdetails',
            name='contact_no_offline_consultation',
            field=models.CharField(blank=True, help_text='10 digit mobile number or 11 digit landline number', max_length=11, null=True, validators=[helper.validators.mobile_validator]),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='contact_no_online_consultation',
            field=models.CharField(blank=True, help_text='10 digit mobile number or 11 digit landline number', max_length=11, null=True, validators=[helper.validators.mobile_validator]),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='contact_no_outdoor_consultation',
            field=models.CharField(blank=True, help_text='10 digit mobile number or 11 digit landline number', max_length=11, null=True, validators=[helper.validators.mobile_validator]),
        ),
        migrations.AlterField(
            model_name='offlineavailability',
            name='contact_no_offline_consultation',
            field=models.CharField(help_text='10 digit mobile number or 11 digit landline number', max_length=11, validators=[helper.validators.mobile_validator]),
        )
    ]
