# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-31 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20190831_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offlineavailability',
            old_name='contact_no_offline_consultation',
            new_name='contact_no',
        )
    ]
