# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_address_country'),
        ('userprofile', '0012_auto_20190217_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='associated_with',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='languages_can_speak',
            field=models.ManyToManyField(to='common.Language'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.ManyToManyField(to='common.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='research',
            field=models.ManyToManyField(to='common.Research'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ManyToManyField(to='common.Specialization'),
        )
    ]
