# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20190831_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrepresentative',
            name='registration_number',
            field=models.CharField(default='', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='registration_number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='aadhaar_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        )
    ]
