# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_discipline'),
        ('userprofile', '0013_auto_20190420_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='research',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='discipline',
            field=models.ManyToManyField(to='common.Discipline'),
        )
    ]
