# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20190902_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationdetails',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_details', to='userprofile.DoctorProfile', unique=True),
        ),
    ]
