# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 12:19
from __future__ import unicode_literals

import common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_discipline'),
        ('userprofile', '0014_auto_20190420_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='achievement_research',
            field=models.TextField(blank=True, help_text='Achievements and researches', null=True, verbose_name=common.models.Research),
        )
    ]
