# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-07 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20190902_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='aadhaar_no',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='have_mediclaim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='identity_card_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='identity_card_type',
            field=models.CharField(choices=[('', ' -- '), ('uid', 'Aadhaar Card (UID)'), ('pp', 'Passport'), ('dl', 'Driving License'), ('vid', 'Voter ID Card '), ('pan', 'Pan Card'), ('cid', 'Company ID Card')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='referred_by',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='consultationdetails',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='userprofile.DoctorProfile'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='documents/patient/'),
        ),
    ]
