# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20190902_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('97b9db42-cfc9-4e7f-af74-04bcb0df8e50'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('97b9db42-cfc9-4e7f-af74-04bcb0df8e50'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('97b9db42-cfc9-4e7f-af74-04bcb0df8e50'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('97b9db42-cfc9-4e7f-af74-04bcb0df8e50'), editable=False, unique=True),
        ),
    ]
