# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_discipline'),
        ('userprofile', '0015_auto_20190420_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='achievement_research',
            field=models.TextField(blank=True, help_text='Achievements and researches', null=True),
        )
    ]
