# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20190907_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='identity_card_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
