# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-11 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20190907_1041'),
        ('userprofile', '0015_auto_20200411_1611'),
    ]

    operations = [
    ]
