# Generated by Django 3.0.5 on 2020-04-10 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helper.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200410_1221'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0016_auto_20190907_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterConsultationFeeDiscountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('offline_consultation_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('offline_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_no_offline_consultation', models.CharField(blank=True, help_text='10 digit mobile number or 11 digit landline number', max_length=11, null=True, validators=[helper.validators.mobile_validator])),
                ('contact_no_online_consultation', models.CharField(blank=True, help_text='10 digit mobile number or 11 digit landline number', max_length=11, null=True, validators=[helper.validators.mobile_validator])),
                ('chat_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('video_call_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('voice_call_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('chat_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('video_call_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('voice_call_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_no_outdoor_consultation', models.CharField(blank=True, help_text='10 digit mobile number or 11 digit landline number', max_length=11, null=True, validators=[helper.validators.mobile_validator])),
                ('outdoor_consultation_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('outdoor_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('outdoor_additional_charges', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masterconsultationfeediscountdetails_created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='offlineavailability',
            old_name='offline_consultation_fee',
            new_name='consultation_fee',
        ),
        migrations.RenameField(
            model_name='offlineavailability',
            old_name='offline_discount',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='authority_registered_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.RegistrationAuthority'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctorprofile_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctorprofile_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('5ab76830-efbb-45e4-9fd2-4a5dc5c2b95f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='healthworkerprofile_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='healthworkerprofile_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('5ab76830-efbb-45e4-9fd2-4a5dc5c2b95f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicalrepresentative_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicalrepresentative_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('5ab76830-efbb-45e4-9fd2-4a5dc5c2b95f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='offlineavailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offlineavailability_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offlineavailability',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offlineavailability_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offlineavailability',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_offlineavailability', to='userprofile.AvailabilitySchedule'),
        ),
        migrations.AlterField(
            model_name='onlineavailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onlineavailability_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onlineavailability',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onlineavailability_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onlineavailability',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_onlineavailability', to='userprofile.AvailabilitySchedule'),
        ),
        migrations.AlterField(
            model_name='outdooravailability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outdooravailability_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outdooravailability',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outdooravailability_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outdooravailability',
            name='outdoor_travel_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outdoor_availabilities', to='common.State'),
        ),
        migrations.AlterField(
            model_name='outdooravailability',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_outdooravailability', to='userprofile.AvailabilitySchedule'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patientprofile_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patientprofile_edited_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='identity_card_type',
            field=models.CharField(choices=[('', ' -- '), ('uid', 'Aadhaar Card (UID)'), ('pp', 'Passport'), ('dl', 'Driving License'), ('vid', 'Voter ID Card '), ('pan', 'Pan Card'), ('cid', 'Company ID Card')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('5ab76830-efbb-45e4-9fd2-4a5dc5c2b95f'), editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='ConsultationDetails',
        ),
        migrations.AddField(
            model_name='masterconsultationfeediscountdetails',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='userprofile.DoctorProfile'),
        ),
        migrations.AddField(
            model_name='masterconsultationfeediscountdetails',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masterconsultationfeediscountdetails_edited_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
