# Generated by Django 2.2 on 2020-04-11 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_auto_20200410_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/doctor/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('19bf42a3-e548-4c5c-85ac-9e3934206a69'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/healthworker/'),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('19bf42a3-e548-4c5c-85ac-9e3934206a69'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/medicalrepresentative/'),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('19bf42a3-e548-4c5c-85ac-9e3934206a69'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('19bf42a3-e548-4c5c-85ac-9e3934206a69'), editable=False, unique=True),
        ),
    ]
