# Generated by Django 2.2 on 2020-04-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_auto_20200411_2108'),
        ('userprofile', '0017_merge_20200411_1618'),
    ]

    operations = [
    ]
