# Generated by Django 2.2 on 2020-04-12 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200410_1221'),
        ('userprofile', '0018_auto_20200411_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='have_mediclaim',
            new_name='medi_insurance',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='case_summary',
            new_name='problem_summary',
        ),
        migrations.AddField(
            model_name='medicalrepresentative',
            name='achievements',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicalrepresentative',
            name='authority_registered_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.RegistrationAuthority'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='relationship',
            field=models.CharField(choices=[('', ' -- '), ('se', 'Self'), ('fa', 'Father'), ('mo', 'Mother'), ('sp', 'Spouse'), ('ch', 'Child')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('97c6fdd5-7fda-4fcd-879c-199e16cfc000'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('97c6fdd5-7fda-4fcd-879c-199e16cfc000'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('97c6fdd5-7fda-4fcd-879c-199e16cfc000'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('97c6fdd5-7fda-4fcd-879c-199e16cfc000'), editable=False, unique=True),
        ),
    ]
