# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_registrationauthority'),
        ('userprofile', '0018_auto_20190420_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='authority_registered_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.RegistrationAuthority'),
        ),
    ]
