# Generated by Django 2.2 on 2020-04-12 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_auto_20200412_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='relationship',
            new_name='relation_with_user',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('e8d18a5b-9e33-4115-825b-fec22da12289'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('e8d18a5b-9e33-4115-825b-fec22da12289'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('e8d18a5b-9e33-4115-825b-fec22da12289'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('e8d18a5b-9e33-4115-825b-fec22da12289'), editable=False, unique=True),
        ),
    ]
