# Generated by Django 2.2 on 2020-04-12 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_auto_20200412_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='relation_with_user',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='relationship_with_user',
            field=models.CharField(choices=[('', ' -- '), ('se', 'Self'), ('fa', 'Father'), ('mo', 'Mother'), ('sp', 'Spouse'), ('ch', 'Child'), ('ot', 'Other')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('ed6067f9-a891-4a05-91f0-faad7de4ba4a'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('ed6067f9-a891-4a05-91f0-faad7de4ba4a'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('ed6067f9-a891-4a05-91f0-faad7de4ba4a'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('ed6067f9-a891-4a05-91f0-faad7de4ba4a'), editable=False, unique=True),
        ),
    ]
