# Generated by Django 2.2 on 2020-04-18 10:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_allergy_disease_immunization_lifestyle_surgery'),
        ('userprofile', '0021_auto_20200412_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworkerprofile',
            name='achievement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='healthworkerprofile',
            name='authority_registered_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.RegistrationAuthority'),
        ),
        migrations.AddField(
            model_name='healthworkerprofile',
            name='certification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='alcohol_addiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergy',
            field=models.ManyToManyField(related_name='patients', to='common.Allergy'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='existing_disease',
            field=models.ManyToManyField(related_name='patients', to='common.Disease'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='immunization',
            field=models.ManyToManyField(related_name='patients', to='common.Immunization'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lifestyle',
            field=models.ManyToManyField(related_name='patients', to='common.Lifestyle'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='smoking_addiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='surgery',
            field=models.ManyToManyField(related_name='patients', to='common.Surgery'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('9c6418d1-7790-4312-8670-8dce37dd143f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('9c6418d1-7790-4312-8670-8dce37dd143f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('9c6418d1-7790-4312-8670-8dce37dd143f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='common.BloodGroup'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='referred_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('9c6418d1-7790-4312-8670-8dce37dd143f'), editable=False, unique=True),
        ),
    ]
