# Generated by Django 2.2 on 2020-04-18 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0022_auto_20200418_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b2659e8a-cf44-42a2-b560-e5268fae42a4'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b2659e8a-cf44-42a2-b560-e5268fae42a4'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b2659e8a-cf44-42a2-b560-e5268fae42a4'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='patients', to='common.Allergy'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='existing_disease',
            field=models.ManyToManyField(blank=True, related_name='patients', to='common.Disease'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='immunization',
            field=models.ManyToManyField(blank=True, related_name='patients', to='common.Immunization'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='surgery',
            field=models.ManyToManyField(blank=True, related_name='patients', to='common.Surgery'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b2659e8a-cf44-42a2-b560-e5268fae42a4'), editable=False, unique=True),
        ),
    ]
