# Generated by Django 2.2 on 2020-04-18 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_auto_20200418_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('8818db67-1ee8-4cbf-b637-fc08b0561653'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('8818db67-1ee8-4cbf-b637-fc08b0561653'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('8818db67-1ee8-4cbf-b637-fc08b0561653'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='lifestyle',
            field=models.ManyToManyField(blank=True, related_name='patients', to='common.Lifestyle'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('8818db67-1ee8-4cbf-b637-fc08b0561653'), editable=False, unique=True),
        ),
    ]
