# Generated by Django 2.2 on 2020-04-18 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_auto_20200418_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('011d879e-40ab-4891-88a1-5897b44e6376'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('011d879e-40ab-4891-88a1-5897b44e6376'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masterconsultationfeediscountdetails',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_details', to='userprofile.DoctorProfile'),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('011d879e-40ab-4891-88a1-5897b44e6376'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('011d879e-40ab-4891-88a1-5897b44e6376'), editable=False, unique=True),
        ),
    ]
