# Generated by Django 2.2 on 2020-04-18 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_auto_20200418_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('957a2b48-a863-4794-b94b-5e1d6d77c64d'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('957a2b48-a863-4794-b94b-5e1d6d77c64d'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masterconsultationfeediscountdetails',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_detail', to='userprofile.DoctorProfile'),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('957a2b48-a863-4794-b94b-5e1d6d77c64d'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('957a2b48-a863-4794-b94b-5e1d6d77c64d'), editable=False, unique=True),
        ),
    ]
