# Generated by Django 2.2 on 2020-04-18 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_auto_20200418_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('28bda28e-571a-4eda-a45d-10f62da39112'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('28bda28e-571a-4eda-a45d-10f62da39112'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('28bda28e-571a-4eda-a45d-10f62da39112'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('28bda28e-571a-4eda-a45d-10f62da39112'), editable=False, unique=True),
        ),
    ]
