# Generated by Django 2.2 on 2020-04-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_merge_20200411_1709'),
        ('userprofile', '0027_auto_20200418_1727'),
    ]

    operations = [
    ]
