# Generated by Django 2.2 on 2020-04-26 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alcoholaddiction_healthworkerregistrationauthority_injury_pathlogylabtype'),
        ('userprofile', '0027_auto_20200418_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='injury',
            field=models.ManyToManyField(blank=True, related_name='patients', to='common.Injury'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('15e8c891-8a51-4d3b-902c-600300258076'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='authority_registered_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.HealthWorkerRegistrationAuthority'),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('15e8c891-8a51-4d3b-902c-600300258076'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('15e8c891-8a51-4d3b-902c-600300258076'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='alcohol_addiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='common.AlcoholAddiction'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('15e8c891-8a51-4d3b-902c-600300258076'), editable=False, unique=True),
        ),
    ]
