# Generated by Django 2.2 on 2020-05-03 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0028_auto_20200426_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='identity_card_type',
            field=models.CharField(choices=[('', ' -- '), ('uid', 'Aadhaar Card (UID)'), ('cid', 'Company ID Card'), ('dl', 'Driving License'), ('pan', 'Pan Card'), ('pp', 'Passport'), ('vid', 'Voter ID Card ')], default='', max_length=3),
        )
    ]
