# Generated by Django 2.2 on 2020-04-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0028_auto_20200426_2151'),
        ('userprofile', '0028_merge_20200418_1214'),
    ]

    operations = [
    ]
