# Generated by Django 2.2 on 2020-04-26 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0029_merge_20200426_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('a2d8ec81-6541-42e6-93da-beaad36bc3a3'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='healthworkerprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('a2d8ec81-6541-42e6-93da-beaad36bc3a3'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('a2d8ec81-6541-42e6-93da-beaad36bc3a3'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('a2d8ec81-6541-42e6-93da-beaad36bc3a3'), editable=False, unique=True),
        ),
    ]
