# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import helper.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=10, validators=[helper.validators.mobile_validator])),
                ('token', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
