# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 09:44
from __future__ import unicode_literals

import commons.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.CharField(max_length=10, validators=[commons.validators.mobile_validator]),
        ),
    ]
