# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='license_no',
            field=models.CharField(help_text='Required for hospitals/clinics/medical-stores', max_length=25),
        ),
    ]
