# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-17 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_address_country'),
        ('organization', '0003_auto_20190126_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='organization',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='common.Specialization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_person',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='license_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/org/%Y/%m/%d/'),
        ),
    ]
