# Generated by Django 2.2 on 2020-04-26 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helper.validators


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alcoholaddiction_healthworkerregistrationauthority_injury_pathlogylabtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_auto_20200410_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathalogy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10, validators=[helper.validators.mobile_validator])),
                ('landline_no', models.CharField(blank=True, help_text="Stored as <STD-PHONE_NO>. Ex- '011-32323234' or '07582-676123'", max_length=11, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_establishment', models.DateField(blank=True, max_length=8, null=True)),
                ('accreditation_year', models.PositiveIntegerField(blank=True, max_length=4, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('license_no', models.CharField(blank=True, help_text='Required for hospitals/clinics/medical-stores', max_length=25, null=True)),
                ('head_of_lab', models.CharField(blank=True, max_length=50, null=True)),
                ('license_doc', models.FileField(blank=True, null=True, upload_to='documents/org/%Y/%m/%d/')),
                ('accreditation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Accreditation')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Address')),
                ('associated_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.Pathalogy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathalogy_created_records', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathalogy_edited_records', to=settings.AUTH_USER_MODEL)),
                ('lab_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pathalogies', to='common.PathlogyLabType')),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.OrganizationType')),
                ('specialization', models.ManyToManyField(blank=True, to='common.Specialization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
