# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190217_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='specialization',
            field=models.ManyToManyField(to='common.Specialization'),
        ),
    ]
