# Generated by Django 2.2 on 2020-05-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_pathalogy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathalogy',
            name='org_type',
        ),
    ]
