# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-03 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20190420_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='contact_no',
            new_name='mobile_no',
        ),
        migrations.AddField(
            model_name='organization',
            name='landline_no',
            field=models.CharField(blank=True, help_text="Stored as <STD-PHONE_NO>. Ex- '011-32323234' or '07582-676123'", max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='common.Specialization'),
        ),
    ]
