# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20190803_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='license_no',
            field=models.CharField(blank=True, help_text='Required for hospitals/clinics/medical-stores', max_length=25, null=True),
        ),
    ]
