# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190803_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
