# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusermodel',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
