# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190207_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusermodel',
            name='user_status',
        ),
        migrations.RemoveField(
            model_name='appusermodel',
            name='user_type',
        ),
    ]
