# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190207_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusermodel',
            name='user_status',
            field=models.IntegerField(choices=[('pending_approval', 'Approval Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default=0),
        ),
        migrations.AddField(
            model_name='appusermodel',
            name='user_type',
            field=models.IntegerField(choices=[('', ' -- '), ('doctor', 'Doctor'), ('health_worker', 'Health Worker'), ('patient', 'Patient'), ('medical_rep', 'Medical Representative'), ('other', 'Other')], default=0),
        ),
    ]
