# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190207_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusermodel',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
