# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_appusermodel_is_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusermodel',
            name='imei',
        ),
    ]
